# githubRepository=OWNER/REPO
# gpr.user=your-github-username
# gpr.key=your-github-token
autoPublish=false
refreshSnapshots=true
coreCommonVersion=1.0.0
coreDataVersion=1.0.0
coreLoggingVersion=1.0.0
coreExcelVersion=1.0.0
coreTestVersion=1.0.0
coreSecurityOauth2Version=1.0.0
coreWebVersion=1.0.0
coreSecurityVersion=1.0.0
